Cherry pick of 84d8a0f467a9d9ce72ff7f2a1b99f195a916f6fa failed
stdout:
Auto-merging stock_orderpoint_manual_update/static/src/views/stock_orderpoint_list_controller.js
Auto-merging stock_orderpoint_manual_update/models/stock_orderpoint.py
CONFLICT (content): Merge conflict in stock_orderpoint_manual_update/models/stock_orderpoint.py

stderr:
17:49:08.770269 git.c:444               trace: built-in: git cherry-pick 84d8a0f467a9d9ce72ff7f2a1b99f195a916f6fa
error: could not apply 84d8a0f4... [FIX]stock_orderpoint_manual_update:recompute qty
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: