Cherry pick of c095b245dc32a8c18bed2b11fefffb9ebb736dae failed
stdout:
Auto-merging stock_ux/models/stock_warehouse_orderpoint.py
CONFLICT (content): Merge conflict in stock_ux/models/stock_warehouse_orderpoint.py

stderr:
18:22:48.704541 git.c:444               trace: built-in: git cherry-pick c095b245dc32a8c18bed2b11fefffb9ebb736dae
error: could not apply c095b245... [FIX]stock_ux: method
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

closes ingadhoc/stock#690

Signed-off-by: Matias Velazquez <mav@adhoc.com.ar>